----------------------------------------------------------------------------------------------------
-- Star Schema DDL for OT (Company) database - IMPROVED VERSION
-- Creates surrogate-key dimensions used by FACT_SALES
-- 
-- IMPROVEMENTS over original version:
-- 1. DIM_TIME now includes FULL_DATE column for RANGE INTERVAL operations
-- 2. Added CHECK constraints for data validation
-- 3. Improved comments and documentation
-- 
-- Idempotent: safely drops existing objects before (re)creating
-- Oracle SQL
-- Author: Jan Ritt
-- Date: 2025-10-28 (Improved Version)
----------------------------------------------------------------------------------------------------

-- Drop existing dimension tables and sequences if present (ignore errors)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_TIME CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_EMPLOYEE CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIM_STATUS CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END; / 

-- Sequences not used; dimensions use IDENTITY columns
-- Clean up any leftover sequences from earlier revisions to avoid conflicts
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_TIME_SEQ';     EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_PRODUCT_SEQ';  EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_CUSTOMER_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_EMPLOYEE_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END; / 
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_STATUS_SEQ';   EXCEPTION WHEN OTHERS THEN NULL; END; / 

----------------------------------------------------------------------------------------------------
-- DIM_TIME - IMPROVED VERSION
----------------------------------------------------------------------------------------------------
-- IMPROVEMENT: Added FULL_DATE column for RANGE INTERVAL operations in analytic functions
-- This eliminates the need for runtime TO_DATE conversions and improves query performance
-- 
-- Example use case:
--   AVG(amount) OVER (ORDER BY full_date RANGE BETWEEN INTERVAL '10' DAY PRECEDING AND CURRENT ROW)
----------------------------------------------------------------------------------------------------

CREATE TABLE DIM_TIME (
  ID         NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  YEAR       NUMBER        NOT NULL,
  MONTH      NUMBER        NOT NULL,
  DAY        NUMBER        NOT NULL,
  FULL_DATE  DATE          NOT NULL,  -- NEW: Complete date for analytic functions
  CONSTRAINT UQ_DIM_TIME UNIQUE (YEAR, MONTH, DAY),
  CONSTRAINT UQ_DIM_TIME_DATE UNIQUE (FULL_DATE),
  -- Data validation constraints
  CONSTRAINT CHK_DIM_TIME_YEAR  CHECK (YEAR BETWEEN 1900 AND 2100),
  CONSTRAINT CHK_DIM_TIME_MONTH CHECK (MONTH BETWEEN 1 AND 12),
  CONSTRAINT CHK_DIM_TIME_DAY   CHECK (DAY BETWEEN 1 AND 31)
);

COMMENT ON TABLE DIM_TIME IS 'Time dimension with date components and full date for analytics';
COMMENT ON COLUMN DIM_TIME.ID IS 'Surrogate key (auto-generated)';
COMMENT ON COLUMN DIM_TIME.YEAR IS 'Year component (1900-2100)';
COMMENT ON COLUMN DIM_TIME.MONTH IS 'Month component (1-12)';
COMMENT ON COLUMN DIM_TIME.DAY IS 'Day component (1-31)';
COMMENT ON COLUMN DIM_TIME.FULL_DATE IS 'Complete date - optimal for RANGE INTERVAL in analytic functions';

----------------------------------------------------------------------------------------------------
-- DIM_PRODUCT (denormalized with category) - IMPROVED VERSION
----------------------------------------------------------------------------------------------------
-- IMPROVEMENT: Added CHECK constraints for price validation
----------------------------------------------------------------------------------------------------

CREATE TABLE DIM_PRODUCT (
  ID                 NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PRODUCT_NAME       VARCHAR2(255)  NOT NULL,
  CATEGORY_NAME      VARCHAR2(255)  NOT NULL,
  STANDARD_COST      NUMBER(9,2),
  LIST_PRICE         NUMBER(9,2),
  SOURCE_PRODUCT_ID  NUMBER         NOT NULL,
  CONSTRAINT UQ_DIM_PRODUCT_SRC UNIQUE (SOURCE_PRODUCT_ID),
  -- Data validation constraints
  CONSTRAINT CHK_DIM_PRODUCT_COST CHECK (STANDARD_COST IS NULL OR STANDARD_COST >= 0),
  CONSTRAINT CHK_DIM_PRODUCT_PRICE CHECK (LIST_PRICE IS NULL OR LIST_PRICE >= 0),
  CONSTRAINT CHK_DIM_PRODUCT_MARGIN CHECK (
    STANDARD_COST IS NULL OR LIST_PRICE IS NULL OR LIST_PRICE >= STANDARD_COST
  )
);

COMMENT ON TABLE DIM_PRODUCT IS 'Product dimension (denormalized with category)';
COMMENT ON COLUMN DIM_PRODUCT.ID IS 'Surrogate key (auto-generated)';
COMMENT ON COLUMN DIM_PRODUCT.PRODUCT_NAME IS 'Product name';
COMMENT ON COLUMN DIM_PRODUCT.CATEGORY_NAME IS 'Product category (denormalized for performance)';
COMMENT ON COLUMN DIM_PRODUCT.STANDARD_COST IS 'Standard cost (must be >= 0)';
COMMENT ON COLUMN DIM_PRODUCT.LIST_PRICE IS 'List price (must be >= standard_cost)';
COMMENT ON COLUMN DIM_PRODUCT.SOURCE_PRODUCT_ID IS 'Original product_id from OLTP system';

----------------------------------------------------------------------------------------------------
-- DIM_CUSTOMER - IMPROVED VERSION
----------------------------------------------------------------------------------------------------
-- IMPROVEMENT: Added CHECK constraint for credit limit validation
----------------------------------------------------------------------------------------------------

CREATE TABLE DIM_CUSTOMER (
  ID                  NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CUSTOMER_NAME       VARCHAR2(255)  NOT NULL,
  ADDRESS             VARCHAR2(255),
  WEBSITE             VARCHAR2(255),
  CREDIT_LIMIT        NUMBER(8,2),
  SOURCE_CUSTOMER_ID  NUMBER         NOT NULL,
  CONSTRAINT UQ_DIM_CUSTOMER_SRC UNIQUE (SOURCE_CUSTOMER_ID),
  -- Data validation constraints
  CONSTRAINT CHK_DIM_CUSTOMER_CREDIT CHECK (CREDIT_LIMIT IS NULL OR CREDIT_LIMIT >= 0)
);

COMMENT ON TABLE DIM_CUSTOMER IS 'Customer dimension';
COMMENT ON COLUMN DIM_CUSTOMER.ID IS 'Surrogate key (auto-generated)';
COMMENT ON COLUMN DIM_CUSTOMER.CUSTOMER_NAME IS 'Customer name';
COMMENT ON COLUMN DIM_CUSTOMER.CREDIT_LIMIT IS 'Credit limit (must be >= 0)';
COMMENT ON COLUMN DIM_CUSTOMER.SOURCE_CUSTOMER_ID IS 'Original customer_id from OLTP system';

----------------------------------------------------------------------------------------------------
-- DIM_EMPLOYEE (salesperson) - IMPROVED VERSION
----------------------------------------------------------------------------------------------------
-- IMPROVEMENT: Added CHECK constraint for hire date validation
----------------------------------------------------------------------------------------------------

CREATE TABLE DIM_EMPLOYEE (
  ID                   NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  FIRST_NAME           VARCHAR2(255)  NOT NULL,
  LAST_NAME            VARCHAR2(255)  NOT NULL,
  EMAIL                VARCHAR2(255)  NOT NULL,
  PHONE                VARCHAR2(50)   NOT NULL,
  HIRE_DATE            DATE           NOT NULL,
  JOB_TITLE            VARCHAR2(255)  NOT NULL,
  SOURCE_EMPLOYEE_ID   NUMBER         NOT NULL,
  CONSTRAINT UQ_DIM_EMPLOYEE_SRC UNIQUE (SOURCE_EMPLOYEE_ID),
  CONSTRAINT UQ_DIM_EMPLOYEE_EMAIL UNIQUE (EMAIL),
  -- Data validation constraints
  CONSTRAINT CHK_DIM_EMPLOYEE_HIREDATE CHECK (HIRE_DATE <= SYSDATE)
);

COMMENT ON TABLE DIM_EMPLOYEE IS 'Employee dimension (salesperson)';
COMMENT ON COLUMN DIM_EMPLOYEE.ID IS 'Surrogate key (auto-generated)';
COMMENT ON COLUMN DIM_EMPLOYEE.HIRE_DATE IS 'Hire date (must be in the past)';
COMMENT ON COLUMN DIM_EMPLOYEE.SOURCE_EMPLOYEE_ID IS 'Original employee_id from OLTP system';

----------------------------------------------------------------------------------------------------
-- DIM_STATUS (order status as small dimension)
----------------------------------------------------------------------------------------------------
-- No changes needed - original version is optimal
----------------------------------------------------------------------------------------------------

CREATE TABLE DIM_STATUS (
  ID      NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STATUS  VARCHAR2(20)  NOT NULL,
  CONSTRAINT UQ_DIM_STATUS UNIQUE (STATUS)
);

COMMENT ON TABLE DIM_STATUS IS 'Order status dimension';
COMMENT ON COLUMN DIM_STATUS.ID IS 'Surrogate key (auto-generated)';
COMMENT ON COLUMN DIM_STATUS.STATUS IS 'Status text (Shipped, Pending, Canceled, etc.)';

----------------------------------------------------------------------------------------------------
-- Summary of improvements:
-- ✅ DIM_TIME.FULL_DATE added for better analytic function support
-- ✅ CHECK constraints for data validation
-- ✅ Comments on tables and columns
-- ✅ Additional UNIQUE constraints where appropriate
----------------------------------------------------------------------------------------------------

COMMIT;
